source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Demo

  target 'DemoTests' do
    pod 'Masonry'
  end

  target 'DemoUITests' do
    # Pods for testing
  end

end
